name: Build_Arcadyan_AW1000

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      log_switch:
        description: "Compile log switch"
        required: false
        default: "false"
        type: boolean
        options:
          - true
          - false
  
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  CONFIG_FILE: 'config/Arcadyan_AW1000.config' 
  REPO_BRANCH: master
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Kuala_Lumpur
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3  

    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/LeeHe-gif/depend_ubuntu2204_openwrt/main/depend_ubuntu2204_openwrt)
        sudo timedatectl set-timezone "${TZ}"
        echo "status=success" >> ${GITHUB_OUTPUT}
        
    - name: Clone source code
      id: codes
      if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        cat <<EOF >> feeds.conf.default
        src-git modem https://github.com/FUjr/QModem.git;main
        src-git istore https://github.com/linkease/istore;main
        src-git nas https://github.com/linkease/nas-packages.git;master
        src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main
        src-git modem_app https://github.com/intannajwa/custom-app.git
        EOF

    - name: Free up disk space
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/{dl,staging_dir,build_dir}
        sudo chown -R $USER:$GROUPS /mnt/openwrt
        ln -sfn /mnt/openwrt/dl openwrt/dl
        ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
        ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a -f -p modem
        ./scripts/feeds install -d y -p istore luci-app-store
        ./scripts/feeds install -a -p nas
        ./scripts/feeds install -a -p nas_luci

    - name: Configuration Customization - Build_Arcadyan_AW1000
      run: |
        if [[ ! -f "${CONFIG_FILE}" ]]; then
          echo "❌ Error: Config file ${CONFIG_FILE} does not exist"
          ls -l config/ || true
          exit 1
        fi
        chmod +x ./customize.sh && ./customize.sh
        [[ -d "files" ]] && mv -f files openwrt/files
        cp -fv "${CONFIG_FILE}" openwrt/.config
        cd openwrt && make defconfig
        
    - name: Download package
      id: package
      run: |
        cd openwrt/
        make download -j$(nproc) || { echo "❌ Download failed"; exit 1; }
        find dl -size -1024c -delete  

    - name: Compile the OpenWrt
      id: compile
      run: |
        cd openwrt/
        if [[ "${{ inputs.log_switch }}" == "yes" ]]; then
            make -j1 V=s
        else
            make -j$(nproc)
        fi
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/* 
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}/*

    - name: Generate release info
      id : release
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        cat <<EOF > release.txt
        🚀 OpenWrt Firmware Build Results
        ----------------------
        Device: Arcadyan_AW1000
        Time: $(date +"%Y-%m-%d %H:%M")
        Source: $REPO_URL
        Branch: $REPO_BRANCH
        EOF

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.compile.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Cleanup workflow runs
      uses: LeeHe-gif/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        token: ${{ secrets.GITHUB_TOKEN }}
